/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;

/**
 *
 * @author yael_
 */
public class Login extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Login2
     */
    public Login() {
        initComponents();
        Manejador m = new Manejador();
        lblCrearCuenta.addMouseListener(m);
        btnLogin.addActionListener(this);
        lblOlvidarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirNavegador("https://www.google.com");
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOlvidarPassword.setFont(new Font("Segoe UI", Font.BOLD, 13));
                lblOlvidarPassword.setForeground(Color.blue);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOlvidarPassword.setFont(new Font("Segoe UI", Font.PLAIN, 12));
                lblOlvidarPassword.setForeground(Color.black);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword = new javax.swing.JPasswordField();
        txtUsuario = new java.awt.TextField();
        lblOlvidarPassword = new javax.swing.JLabel();
        lblError1 = new javax.swing.JLabel();
        lblError2 = new javax.swing.JLabel();
        lblCrearCuenta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jpIngles = new javax.swing.JPanel();
        jcbRecordar = new javax.swing.JCheckBox();
        jpSpanish = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesion");
        setResizable(false);
        setSize(new java.awt.Dimension(468, 578));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword.setBorder(null);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 130, 25));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 130, 25));

        lblOlvidarPassword.setText("¿olvidaste tu contraseña?");
        lblOlvidarPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblOlvidarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 160, 20));

        lblError1.setForeground(new java.awt.Color(255, 60, 30));
        getContentPane().add(lblError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 150, 15));

        lblError2.setForeground(new java.awt.Color(255, 60, 30));
        getContentPane().add(lblError2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 150, 15));

        lblCrearCuenta.setText("click aquí");
        lblCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 60, 20));

        jLabel1.setText("¿no tienes cuenta? ");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 110, 20));

        btnLogin.setBackground(new java.awt.Color(110, 108, 110));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonStart.png"))); // NOI18N
        btnLogin.setBorder(null);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setMaximumSize(new java.awt.Dimension(100, 41));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 100, 41));

        jpIngles.setToolTipText("Ingles");
        jpIngles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpIngles.setOpaque(false);

        javax.swing.GroupLayout jpInglesLayout = new javax.swing.GroupLayout(jpIngles);
        jpIngles.setLayout(jpInglesLayout);
        jpInglesLayout.setHorizontalGroup(
            jpInglesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jpInglesLayout.setVerticalGroup(
            jpInglesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jpIngles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 45, 30, 20));

        jcbRecordar.setBackground(new java.awt.Color(110, 108, 110));
        jcbRecordar.setText("Recordar usuario");
        jcbRecordar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jcbRecordar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 415, -1, -1));

        jpSpanish.setToolTipText("Español");
        jpSpanish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpSpanish.setOpaque(false);
        jpSpanish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpSpanishMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jpSpanishLayout = new javax.swing.GroupLayout(jpSpanish);
        jpSpanish.setLayout(jpSpanishLayout);
        jpSpanishLayout.setHorizontalGroup(
            jpSpanishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jpSpanishLayout.setVerticalGroup(
            jpSpanishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jpSpanish, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 20));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LoginSesionConRegionSinTxt.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 462, 578));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setIcon(new ImageIcon(getClass().getResource("/Imagenes/BotonStartPulsado.png")));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnLogin.setIcon(new ImageIcon(getClass().getResource("/Imagenes/BotonStart.png")));
    }//GEN-LAST:event_btnLoginMouseExited

    private void jpSpanishMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpSpanishMouseEntered
        jpSpanish.setOpaque(true);
    }//GEN-LAST:event_jpSpanishMouseEntered

    public void actionPerformed(java.awt.event.ActionEvent evt){
        if(txtUsuario.getText().equals("admin") && txtPassword.getText().equals("admin")){
            Main ventana = new Main();
            ventana.setVisible(true);
            this.dispose();
        }//if usuario y contraseña correctos
        if(!txtUsuario.getText().equals("admin")){
               lblError1.setText("Usuario incorrecto");
               lblError2.setText("");
               return;
        }//if Usuario incorrecto
        if(!txtPassword.getText().equals("admin")){
               lblError2.setText("Contraseña incorrecta");
               lblError1.setText("");
        }//if Contraseña incorrecta
        //showMessageDialog(Login.this, "Sí funciona.");
    }//action performed ventana manejador de eventos
    
    class Manejador implements MouseListener{
        public void mouseClicked(java.awt.event.MouseEvent evt){
            abrirNavegador("https://www.tepic.tecnm.mx");
        }//mouseclicked
        public void mouseExited(java.awt.event.MouseEvent evt){
            lblCrearCuenta.setFont(new Font("Segoe UI", Font.PLAIN, 12));
            lblCrearCuenta.setForeground(Color.black);
        }//mouseexited
        public void mouseEntered(java.awt.event.MouseEvent evt){
            lblCrearCuenta.setFont(new Font("Segoe UI", Font.BOLD, 13));
            lblCrearCuenta.setForeground(Color.blue);
        }//mouseexited
        public void mouseReleased(java.awt.event.MouseEvent evt){
            
        }//mouseexited
        public void mousePressed(java.awt.event.MouseEvent evt){
            
        }//mouseexited
}//clase manejador
    
    public void abrirNavegador(String Dominio){
        if(java.awt.Desktop.isDesktopSupported()){
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if(desktop.isSupported(Desktop.Action.BROWSE)){
                try{
                    java.net.URI uri = new java.net.URI(Dominio);
                    desktop.browse(uri);
                }catch(URISyntaxException | IOException ex){}
            }//if isSupoorted
        }//if isDesktopSupported
    }//abre el navegador
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox jcbRecordar;
    private javax.swing.JPanel jpIngles;
    private javax.swing.JPanel jpSpanish;
    private javax.swing.JLabel lblCrearCuenta;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblError2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblOlvidarPassword;
    private javax.swing.JPasswordField txtPassword;
    private java.awt.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
