/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author yael_
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCuenta = new javax.swing.JLabel();
        lblTienda = new javax.swing.JLabel();
        lblBiblioteca = new javax.swing.JLabel();
        lblComunidad = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCuenta.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        lblCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblCuenta.setText("Cuenta");
        lblCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 130, 60));

        lblTienda.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        lblTienda.setForeground(new java.awt.Color(255, 255, 255));
        lblTienda.setText("Tienda");
        lblTienda.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(lblTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 120, 60));

        lblBiblioteca.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        lblBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        lblBiblioteca.setText("Biblioteca");
        lblBiblioteca.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(lblBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 180, 60));

        lblComunidad.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        lblComunidad.setForeground(new java.awt.Color(255, 255, 255));
        lblComunidad.setText("Comunidad");
        lblComunidad.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(lblComunidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 210, 60));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MainSinTxt.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBiblioteca;
    private javax.swing.JLabel lblComunidad;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTienda;
    // End of variables declaration//GEN-END:variables
}
