/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MenuPrincipal;

import java.io.Serializable;

/**
 *
 * @author yael_
 */
public class Principal extends javax.swing.JPanel implements Serializable {
     
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Menu1.setVisible(false);
        Menu2.setVisible(false);
        Menu3.setVisible(false);
        Menu4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDezlizante = new javax.swing.JLabel();
        Contenedor1 = new javax.swing.JPanel();
        Opcion1 = new javax.swing.JLabel();
        Separador1 = new javax.swing.JLabel();
        Contenedor2 = new javax.swing.JPanel();
        Opcion2 = new javax.swing.JLabel();
        Separador2 = new javax.swing.JLabel();
        Contenedor3 = new javax.swing.JPanel();
        Opcion3 = new javax.swing.JLabel();
        Separador3 = new javax.swing.JLabel();
        Contenedor4 = new javax.swing.JPanel();
        lblOpcion4 = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Menu1 = new javax.swing.JPanel();
        Menu2 = new javax.swing.JPanel();
        Menu3 = new javax.swing.JPanel();
        Menu4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(110, 150, 180));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDezlizante.setBackground(new java.awt.Color(110, 108, 110));
        lblDezlizante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDezlizante.setText("Icono");
        lblDezlizante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblDezlizante, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 0, 50, 50));

        Contenedor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Contenedor1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Contenedor1MouseExited(evt);
            }
        });
        Contenedor1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Opcion1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Opcion1.setText("Tienda");
        Contenedor1.add(Opcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        Separador1.setText("Icono");
        Separador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Contenedor1.add(Separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 40, 50));

        add(Contenedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        Contenedor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Contenedor2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Contenedor2MouseExited(evt);
            }
        });
        Contenedor2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Opcion2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Opcion2.setText("Biblioteca");
        Contenedor2.add(Opcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 50));

        Separador2.setText("Icono");
        Separador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Contenedor2.add(Separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 40, 50));

        add(Contenedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 200, 50));

        Contenedor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Contenedor3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Contenedor3MouseExited(evt);
            }
        });
        Contenedor3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Opcion3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Opcion3.setText("Comunidad");
        Contenedor3.add(Opcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 185, 50));

        Separador3.setText("Icono");
        Separador3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Contenedor3.add(Separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 0, 40, 50));

        add(Contenedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 225, 50));

        Contenedor4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Contenedor4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Contenedor4MouseExited(evt);
            }
        });

        lblOpcion4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblOpcion4.setText("Cuenta");

        lblIcono.setBackground(new java.awt.Color(110, 108, 110));
        lblIcono.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblIcono.setText("Icono");

        javax.swing.GroupLayout Contenedor4Layout = new javax.swing.GroupLayout(Contenedor4);
        Contenedor4.setLayout(Contenedor4Layout);
        Contenedor4Layout.setHorizontalGroup(
            Contenedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contenedor4Layout.createSequentialGroup()
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOpcion4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Contenedor4Layout.setVerticalGroup(
            Contenedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contenedor4Layout.createSequentialGroup()
                .addGroup(Contenedor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOpcion4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(Contenedor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 0, 160, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu1.setBackground(new java.awt.Color(110, 108, 110));

        javax.swing.GroupLayout Menu1Layout = new javax.swing.GroupLayout(Menu1);
        Menu1.setLayout(Menu1Layout);
        Menu1Layout.setHorizontalGroup(
            Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        Menu1Layout.setVerticalGroup(
            Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Menu2.setBackground(new java.awt.Color(110, 108, 110));

        javax.swing.GroupLayout Menu2Layout = new javax.swing.GroupLayout(Menu2);
        Menu2.setLayout(Menu2Layout);
        Menu2Layout.setHorizontalGroup(
            Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        Menu2Layout.setVerticalGroup(
            Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 200, -1));

        Menu3.setBackground(new java.awt.Color(110, 108, 110));

        javax.swing.GroupLayout Menu3Layout = new javax.swing.GroupLayout(Menu3);
        Menu3.setLayout(Menu3Layout);
        Menu3Layout.setHorizontalGroup(
            Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        Menu3Layout.setVerticalGroup(
            Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 225, -1));

        Menu4.setBackground(new java.awt.Color(110, 108, 110));

        javax.swing.GroupLayout Menu4Layout = new javax.swing.GroupLayout(Menu4);
        Menu4.setLayout(Menu4Layout);
        Menu4Layout.setHorizontalGroup(
            Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        Menu4Layout.setVerticalGroup(
            Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 0, 160, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 785, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void Contenedor1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contenedor1MouseEntered
        Menu1.setVisible(true);
    }//GEN-LAST:event_Contenedor1MouseEntered

    private void Contenedor1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contenedor1MouseExited
        Menu1.setVisible(false);
    }//GEN-LAST:event_Contenedor1MouseExited

    private void Contenedor2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contenedor2MouseEntered
        Menu2.setVisible(true);
    }//GEN-LAST:event_Contenedor2MouseEntered

    private void Contenedor2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contenedor2MouseExited
        Menu2.setVisible(false);
    }//GEN-LAST:event_Contenedor2MouseExited

    private void Contenedor3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contenedor3MouseEntered
        Menu3.setVisible(true);
    }//GEN-LAST:event_Contenedor3MouseEntered

    private void Contenedor3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contenedor3MouseExited
        Menu3.setVisible(false);
    }//GEN-LAST:event_Contenedor3MouseExited

    private void Contenedor4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contenedor4MouseEntered
        Menu4.setVisible(true);
    }//GEN-LAST:event_Contenedor4MouseEntered

    private void Contenedor4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contenedor4MouseExited
        Menu4.setVisible(false);
    }//GEN-LAST:event_Contenedor4MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor1;
    private javax.swing.JPanel Contenedor2;
    private javax.swing.JPanel Contenedor3;
    private javax.swing.JPanel Contenedor4;
    private javax.swing.JPanel Menu1;
    private javax.swing.JPanel Menu2;
    private javax.swing.JPanel Menu3;
    private javax.swing.JPanel Menu4;
    private javax.swing.JLabel Opcion1;
    private javax.swing.JLabel Opcion2;
    private javax.swing.JLabel Opcion3;
    private javax.swing.JLabel Separador1;
    private javax.swing.JLabel Separador2;
    private javax.swing.JLabel Separador3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDezlizante;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblOpcion4;
    // End of variables declaration//GEN-END:variables
}
